apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-worker
  namespace: {{ .Values.namespace }}
  {{- if .Values.worker.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.worker.serviceAccount.roleArn }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
  namespace: {{ .Values.namespace }}
  {{- if .Values.console.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.console.serviceAccount.roleArn }}
  {{- end }}
