{{- if .Values.workerApiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: worker-api-keys
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.workerApiKeys }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
